import React, { Suspense, useMemo, useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { Search, Activity, Users, DollarSign, Database } from 'lucide-react';
import { DashboardData, ProjectData } from './types';
import ProjectCard from './components/ProjectCard';

// Lazy loaded tabs
const TrackerTab = React.lazy(() => import('./components/tabs/TrackerTab'));
const GravityPoolTab = React.lazy(() => import('./components/tabs/GravityPoolTab'));
const SpotlightTab = React.lazy(() => import('./components/tabs/SpotlightTab'));
const WalletAnalyticsTab = React.lazy(() => import('./components/tabs/WalletAnalyticsTab'));

const TABS = [
  { id: 'tracker', label: 'Tracker' },
  { id: 'gravity', label: 'Gravity Pool' },
  { id: 'spotlight', label: 'Spotlight' },
  { id: 'wallet', label: 'Wallet Analytics' }
];

export default function App() {
  const [data, setData] = useState<DashboardData | null>(null);
  const [loading, setLoading] = useState(true);
  const [activeTab, setActiveTab] = useState(TABS[0].id);

  useEffect(() => {
    const fetchData = async () => {
      try {
        // Load strictly from decoupled local cache generated by scripts/fetch-dune.ts
        // This completely avoids live API calls from the client side for 0ms load times
        const res = await fetch('/data/dune-cache.json');
        if (!res.ok) {
          throw new Error("Failed to load local dune cache. Please ensure you ran 'npm run fetch-dune'");
        }
        const json = await res.json();
        setData(json);
      } catch (err) {
        console.error("Failed to load dashboard data", err);
      } finally {
        // Will be near-instant 
        setLoading(false);
      }
    };
    
    fetchData();
    // Removed polling interval to ensure no unnecessary client-side polling 
    // cache is completely static driven by background script.
  }, []);

  const topGainer = useMemo(() => {
    if (!data?.projects || data.projects.length === 0) return null;
    return data.projects.reduce((prev: ProjectData, current: ProjectData) => {
      // Find the one with most volume today
      const prevVol = prev.stats30d?.volume || 0;
      const currentVol = current.stats30d?.volume || 0;
      return (prevVol > currentVol) ? prev : current;
    }, data.projects[0]);
  }, [data?.projects]);

  if (loading || !data) {
    return (
      <div className="flex flex-col items-center justify-center min-h-screen text-abstract-neon bg-[#0D0D0D]">
        <div className="w-16 h-16 relative flex items-center justify-center">
            {/* Sleek dark-mode skeleton spinner */}
            <div className="absolute inset-0 border-4 border-white/5 rounded-full" />
            <div className="absolute inset-0 border-4 border-abstract-neon border-t-transparent rounded-full animate-spin" />
            <Database className="w-6 h-6 text-abstract-neon opacity-80" />
        </div>
        <h2 className="text-xl font-medium tracking-tight text-white mt-6 mb-2">Analyzing Genesis Ecosystem...</h2>
        <div className="w-48 h-1 bg-white/5 rounded-full overflow-hidden">
            <motion.div 
               className="h-full bg-abstract-neon origin-left"
               initial={{ scaleX: 0 }}
               animate={{ scaleX: 1 }}
               transition={{ duration: 1, repeat: Infinity }}
            />
        </div>
      </div>
    );
  }

  // Calculate some derived global metrics
  // Assume basic mock growth for visual interest
  const totalTrx = data.globalData?.totalTrx30d || 0;
  const tps = (totalTrx / (30 * 24 * 60 * 60)).toFixed(1);
  
  const vol = data.globalData?.totalVolume30d || 0;
  const formattedVolume = vol >= 1e9 
    ? `$${(vol / 1e9).toFixed(2)}B`
    : vol >= 1e6 
      ? `$${(vol / 1e6).toFixed(2)}M`
      : vol >= 1e3
        ? `$${(vol / 1000).toFixed(1)}k`
        : `$${vol.toFixed(0)}`;

  return (
    <div className="font-sans">
      {/* Navbar */}
      <nav className="sticky top-0 z-50 bg-[#0D0D0D]/80 backdrop-blur-xl border-b border-white/5">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
          <div className="flex items-center gap-3">
             <img
               src="/logoeco.png"
               alt="ABS ECO"
               className="w-9 h-9 rounded-lg object-cover border border-white/10"
             />
             <span className="text-lg font-semibold tracking-tight">ABS<span className="text-abstract-neon"> ECO</span></span>
          </div>
          <div className="hidden md:flex relative group">
            <Search className="w-4 h-4 absolute left-3 top-1/2 -translate-y-1/2 text-zinc-500 group-focus-within:text-abstract-neon transition-colors" />
            <input 
              type="text" 
              placeholder="Search projects, contracts..." 
              className="w-64 bg-white/5 border border-white/10 rounded-full py-1.5 pl-10 pr-4 text-sm focus:outline-none focus:border-abstract-neon/50 focus:bg-white/10 transition-all placeholder:text-zinc-600"
            />
          </div>
        </div>
      </nav>

      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 flex flex-col gap-10">
        <section>
          {/* Pill Tab Navigation */}
          <div className="flex overflow-x-auto hide-scrollbar mb-8 border-b border-white/5 pb-1">
            <div className="flex gap-2 p-1 bg-white/[0.02] rounded-full border border-white/5">
              {TABS.map((tab) => (
                <button
                  key={tab.id}
                  onClick={() => setActiveTab(tab.id)}
                  className={`relative px-5 py-2 text-sm font-medium rounded-full transition-colors whitespace-nowrap ${
                    activeTab === tab.id ? 'text-[#0D0D0D]' : 'text-zinc-400 hover:text-white'
                  }`}
                >
                  {activeTab === tab.id && (
                    <motion.div
                      layoutId="active-tab"
                      className="absolute inset-0 bg-abstract-neon rounded-full -z-10 shadow-[0_0_15px_rgba(0,255,102,0.4)]"
                      transition={{ type: 'spring', stiffness: 400, damping: 30 }}
                    />
                  )}
                  <span className="relative z-10">{tab.label}</span>
                </button>
              ))}
            </div>
          </div>

          {/* Tab Content */}
          <div className="min-h-[500px]">
            <Suspense fallback={<TabSkeleton />}>
              <AnimatePresence mode="wait">
                  <motion.div
                    key={activeTab}
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, y: -10 }}
                    transition={{ duration: 0.2 }}
                  >
                    {activeTab === 'tracker' && <TrackerTab data={data} />}
                    {activeTab === 'gravity' && <GravityPoolTab data={data} />}
                    {activeTab === 'spotlight' && <SpotlightTab data={data} />}
                    {activeTab === 'wallet' && <WalletAnalyticsTab data={data} />}
                  </motion.div>
              </AnimatePresence>
            </Suspense>
          </div>
        </section>

        {/* Global Hero Metrics Moved Below */}
        <section className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 pb-12">
          <GlobalMetricCard
            title="Ecosystem Volume (30d)"
            value={formattedVolume}
            icon={<DollarSign className="w-5 h-5" />}
          />
          <GlobalMetricCard
            title="Total Users (30d)"
            value={(data.globalData?.totalUsers30d || 0).toLocaleString()}
            subtitle="(per-project sum)"
            icon={<Users className="w-5 h-5" />}
          />
          <GlobalMetricCard
            title="Total Transactions (30d)"
            value={data.globalData?.totalTrx30d >= 1000000
              ? `${(data.globalData.totalTrx30d / 1000000).toFixed(1)}M`
              : (data.globalData?.totalTrx30d || 0).toLocaleString()}
            subtitle={`~${tps} tx/s avg`}
            icon={<Activity className="w-5 h-5" />}
          />
          {topGainer ? (
            <ProjectCard project={topGainer} label="Top Performer · 30d Vol" glow />
          ) : (
            <GlobalMetricCard
              title="Top Performer"
              value="N/A"
              subtitle="Most Volume 30d"
              icon={<Activity className="w-5 h-5" />}
              glow
            />
          )}
        </section>
      </main>
    </div>
  );
}

function GlobalMetricCard({ title, value, icon, subtitle, glow = false }: { title: string, value: string, icon: React.ReactNode, subtitle?: string, glow?: boolean }) {
  return (
    <div className={`relative p-5 rounded-2xl bg-abstract-card backdrop-blur-md border border-white/5 flex flex-col gap-3 overflow-hidden ${glow ? 'border-abstract-neon/30 shadow-[0_0_30px_rgba(0,255,102,0.05)]' : ''}`}>
       <div className="flex justify-between items-center text-zinc-400">
         <span className="text-sm font-medium">{title}</span>
         <div className={glow ? 'text-abstract-neon' : ''}>{icon}</div>
       </div>
       <div className="flex items-baseline gap-2">
         <span className="text-2xl font-semibold tracking-tight text-white">{value}</span>
         {subtitle && <span className="text-xs text-abstract-neon">{subtitle}</span>}
       </div>
    </div>
  );
}

function TabSkeleton() {
  return (
    <div className="w-full h-[500px] bg-abstract-card border border-white/5 rounded-2xl animate-pulse flex items-center justify-center">
      <div className="flex flex-col items-center gap-3 opacity-50">
        <div className="w-8 h-8 border-2 border-abstract-neon border-t-transparent rounded-full animate-spin" />
        <p className="text-sm text-zinc-500">Loading module...</p>
      </div>
    </div>
  );
}
